# Generated by Django 5.0 on 2024-10-07 12:20

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_booking_activitylog_charger_booking_charger_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='tags',
        ),
        migrations.AddField(
            model_name='station',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
