# Generated by Django 5.0 on 2024-10-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_remove_station_tags_station_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargertype',
            old_name='type',
            new_name='charger_type',
        ),
    ]
