# Generated by Django 5.0 on 2024-10-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_rename_type_chargertype_charger_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargertype',
            old_name='charger_type',
            new_name='type',
        ),
    ]
