# Generated by Django 5.0 on 2024-10-03 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0005_alter_station_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='user',
            new_name='username',
        ),
    ]
