# Generated by Django 5.0 on 2024-10-03 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0006_rename_user_station_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Station',
            new_name='Stations',
        ),
        migrations.RenameField(
            model_name='stations',
            old_name='username',
            new_name='user',
        ),
    ]
