# Generated by Django 5.0 on 2024-10-03 16:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0007_rename_station_stations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stations',
            new_name='Station',
        ),
    ]
