# Generated by Django 5.0 on 2024-10-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0008_rename_stations_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='user',
            new_name='user_name',
        ),
    ]
