# Generated by Django 5.0 on 2024-10-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0009_rename_user_station_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='user_name',
            new_name='user',
        ),
    ]
