# Generated by Django 5.0 on 2024-10-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0010_rename_user_name_station_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
