# Generated by Django 5.0 on 2024-10-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='verfied',
            new_name='verified',
        ),
    ]
